# Generated by Django 3.1 on 2020-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200901_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='uploads', verbose_name='文章标题图片'),
        ),
    ]
